### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by KJLJon** [yiisoft/event-dispatcher#59]
Not a real issue more of a code formatting/style thing

### What steps will reproduce the problem?
I see `use function {php function name}` is being used in multiple places.

I noticed in [Provider](https://github.com/yiisoft/event-dispatcher/blob/41b7ef783a4dc23c71230753726b0c6d3256c615/src/Provider/Provider.php#L8) it only imports one of the functions it uses.

### What is the expected result?
Either all of the functions called out or none of them.

Other functions not called out:
* array_values
* class_parents
* class_implements

### What do you get instead?
`use function get_class;` is only called out and the other functions aren't

### Additional info
N/A

**Comment by vjik** [comment]
Since PHP 7.0, some internal function replaced by opcodes, which are executed much faster. To make it work them need to be prefixed by `\` or declared in section `use`.

List of such functions:

- `array_slice`
- `assert`
- `boolval`
- `call_user_func`
- `call_user_func_array`
- `chr`
- `constant`
- `count`
- `define`
- `defined`
- `dirname`
- `doubleval`
- `extension_loaded`
- `floatval`
- `func_get_args`
- `func_num_args`
- `function_exists`
- `get_called_class`
- `get_class`
- `gettype`
- `in_array`
- `intval`
- `is_array`
- `is_bool`
- `is_callable`
- `is_double`
- `is_float`
- `is_int`
- `is_integer`
- `is_long`
- `is_null`
- `is_object`
- `is_real`
- `is_resource`
- `is_string`
- `ord`
- `strlen`
- `strval`

**Comment by KJLJon** [comment]
I thought there might be some reason, but was googling the wrong things.  :-)

Thanks!
